name: play_XI
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  feather_icons_flutter: ^4.7.4
  flutter_bloc: ^6.1.1
  flutter_phoenix: ^0.1.0
  flutter_spinkit: ^4.1.2+1
  font_awesome: ^5.10.1
  google_fonts: ^1.1.1
  http: ^0.12.2
  provider: ^4.3.2+2
  shared_preferences: ^0.5.12+4
  firebase_auth: ^0.15.3
  google_sign_in: null
  animations: ^1.1.2
  rive:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/
    - assets/rive/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
